# .travis.yml for python-geometry

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - "pip install ."
  - "pip install -r requirements-test.txt"

script: 
  run_tests

after_success:
  coveralls


