# .travis.yml for python-geometry


# before_install
# before_script
# script
# after_success
# after_failure
# after_script (receives TRAVIS_TEST_RESULT)
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "pip install ."
before_script:
  - "pip install unittest2"
script: make test
